name: kekkon_revision
version: 1.0.0+1
publish_to: none
description: Kekkon Revision.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.5
  cupertino_icons: ^1.0.2
  firebase: ^9.0.2
  firebase_auth: ^3.3.1
  firebase_core: ^1.10.6
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.0.0
  flutter_spinkit: ^5.1.0
  flutter_staggered_grid_view: ^0.4.1
  form_builder_validators: ^7.3.0
  get: 4.3.8
  get_storage: ^2.0.3
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  lints: 1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
