name: kekkon_revision
version: 1.0.0+1
publish_to: none
description: Kekkon Revision.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cloud_firestore: ^3.1.5
  cupertino_icons: ^1.0.2
  firebase: ^9.0.2
  firebase_auth: ^3.3.1
  firebase_core: ^1.10.6
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.4.1
  get: 4.3.8

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  lints: 1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
